on: [push]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Deploy
        run: forge create contracts/call.sol:call --private-key ${{ secrets.PRIV }} --rpc-url https://goerli.infura.io/v3/57ce29b969b5410897a117fb29254b41 --constructor-args 0xcfd9741867bad2f94c8bfb91518066436cbe6a20 

      - name: Run snapshot
        run: forge snapshot
